version: '3.9'

services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    environment:
      PUBLIC_KEY: ${PUBLIC_KEY}
      SUDO_ACCESS: ${SUDO_ACCESS}
      USER_NAME: ${USER_NAME}
    volumes:
      - "data:/persistent"
    ports:
      - ${PORT}:2222

volumes:
  data:
    name: ${VOLUME}
