version: '3.9'

services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    environment:
      PUBLIC_KEY: ${PUBLIC_KEY}
      SUDO_ACCESS: ${SUDO_ACCESS}
      USER_NAME: ${USER_NAME}
    deploy:
      placement:
        constraints:
          - "node.hostname==${NODE}"
    volumes:
      - "data:/persistent"
    ports:
      - ${PORT}:2222
    working_dir: "/persistent"

volumes:
  data:
    name: ${VOLUME}
