version: '3.4'
services:
  nginx:
    image: "nginx:latest"
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - volume:/etc/nginx
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.capabilities.web == yes]
  notebook:
    restart: always
    image: jupyter/base-notebook:latest
    user: root
    environment:
      NB_UID: 0
      NB_USER: root
      NB_GID: 0
      NB_GROUP: root
      CHOWN_HOME: yes
    volume:
      - volume:/home/$NB_USER/nginx
    networks:
      - network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
volumes:
  volume:
    name: ${CONF_VOLUME}
networks:
  network:
    driver: overlay
    attachable: true
