version: '3.9'
services:
  nginx:
    image: "nginx:latest"
    restart: always
    depends_on:
      - notebook
    privileged: ${PRIVILEGED}
    # ports:
    #   - ${HTTP_PORT}:80
    #   - ${HTTPS_PORT}:443
    volumes:
      - volume:/etc/nginx
    networks:
      private-network:
      public-network:
        ipv4_address: ${PUBLIC_IP}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.web == yes
  notebook:
    restart: always
    image: jupyter/base-notebook:latest
    user: root
    ports:
      - 8888
    environment:
      NB_UID: 0
      NB_USER: root
      NB_GID: 0
      NB_GROUP: root
      CHOWN_HOME: 'yes'
      GRANT_SUDO: 'yes'
      NOTEBOOK_ARGS: '--allow-root'
    volumes:
      - volume:/home/root/nginx
    networks:
      - private-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
volumes:
  volume:
    name: ${CONF_VOLUME}
networks:
  private-network:
    driver: overlay
  public-network:
    name: ${PUBLIC_NETWORK}
    external: true
