version: '3.4'

services:
  # https://hub.docker.com/r/cschranz/gpu-jupyter
  jupyter:
    image: cschranz/gpu-jupyter:${VERSION}
    volumes:
      - data:/home/jovyan/persistent
    ports:
      - 8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.npu==nvidia
# The resources.reservation.devices option is not currently available in Swarm. 
# Workaround: specifying the devices is not needed if the default runtime
# of the docker daemon running the container is `nvidia`.
# So we're exploiting 2 conventions here:
# 1. guaranteeing this service is executed on a node having the nvidia capability (via the constraint above)
# 2. guaranteeing all nodes labelled as `node.labels.capabilities.npu==nvidia` have `nvidia` as their default runtime
# cf. https://github.com/NVIDIA/nvidia-docker/wiki/Advanced-topics
      # resources:
      #   reservations:
      #     devices:
      #       - capabilities: [gpu]
      #         driver: nvidia
      #         count: 1
volumes:
  data:
    name: ${VOLUME}
