version: '3.4'

services:
  # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
  jupyter:
    image: jupyter/${NOTEBOOK_TYPE}-notebook:${NOTEBOOK_VERSION}
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options
    user: root
    environment:
      NB_USER: ${USER}
      CHOWN_HOME: 'yes'
      GRANT_SUDO: 'yes'
      # pip install jupyter
      # python -c "from notebook.auth import passwd; print(passwd('$PASSWORD'))"
      NOTEBOOK_ARGS: "--NotebookApp.password='${PASSWORD_HASH}'"
    volumes:
      - data:/home/${USER}/persistent
    ports:
      - ${PORT}:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
volumes:
  data:
    name: ${VOLUME}
