version: '3.4'

# docker run -it --rm -p 10000:8888 -v "${PWD}":/home/jovyan/work jupyter/datascience-notebook:0fd03d9356de

services:
  # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
  jupyter:
    image: jupyter/${NOTEBOOK_TYPE}-notebook:${NOTEBOOK_VERSION}
    volumes:
      - data:/home/jovyan/persistent
    ports:
      - 8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
volumes:
  data:
    name: ${VOLUME}
