version: '3.9'

services:
  # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
  jupyter:
    image: jupyter/${NOTEBOOK_TYPE}-notebook:${NOTEBOOK_VERSION}
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options
    user: root
    configs:
      - source: password_generator
        target: /gen-pwd.py
      - source: start_notebook
        target: /start-notebook2.sh
    command: [ "/bin/bash", "/start-notebook2.sh" ]
    environment:
      NB_USER: ${USER}
      CHOWN_HOME: 'yes'
      GRANT_SUDO: 'yes'
    volumes:
      - "data:/home/${USER}/persistent"
      - type: tmpfs
        target: /dev/shm
        tmpfs:
           size: ${SHM_SIZE}
    ports:
      - ${PORT}:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
    secrets:
      - jupyter_password
secrets:
  # mapped into /run/secrets/jupyter_password by default
  jupyter_password:
    external: true
    name: ${PASSWORD_SECRET_NAME}
volumes:
  data:
    name: ${VOLUME}
configs:
  password_generator:
    file: ./gen-pwd.py
  start_notebook:
    file: ./start-notebook2.sh
