version: '3.9'

services:
  # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
  jupyter:
    image: jupyter/${NOTEBOOK_TYPE}-notebook:${NOTEBOOK_VERSION}
    # https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options
    user: root
    configs:
      - source: gen_pwd
        target: /gen-pwd.py
    environment:
      NB_USER: ${USER}
      CHOWN_HOME: 'yes'
      GRANT_SUDO: 'yes'
      # pip install jupyter
      # python -c "from notebook.auth import passwd; print(passwd('$PASSWORD'))"
      NOTEBOOK_ARGS: --NotebookApp.password=$$(python /gen-pwd.py)
    volumes:
      - data:/home/${USER}/persistent
    ports:
      - ${PORT}:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.cpu==yes
    secrets:
      - jupyter_password
secrets:
  # mapped into /run/secrets/jupyter_password by default
  jupyter_password:
    external: true
    name: ${PASSWORD_SECRET_NAME}
volumes:
  data:
    name: ${VOLUME}
configs:
  gen_pwd:
    file: ./gen-pwd.py
