version: '3.9'

services:
  ascend-mindspore-jupyter:
    image: pikalab/ascend-ubuntu-model${MODEL}:latest
    configs:
      - source: password_generator
        target: /gen-pwd.py
      - source: start_notebook
        target: /start-notebook.sh
    command: [ "/bin/bash", "/start-notebook.sh" ]
    volumes:
      - data:/persistent
    ports:
      - ${PORT}:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.labels.capabilities.npu.model==${MODEL} 
          - node.labels.capabilities.npu==huawei
    secrets:
      - jupyter_password
    working_dir: /persistent
secrets:
  # mapped into /run/secrets/jupyter_password by default
  jupyter_password:
    external: true
    name: ${PASSWORD_SECRET_NAME}
volumes:
  data:
    name: ${VOLUME}
configs:
  password_generator:
    file: ./gen-pwd.py
  start_notebook:
    file: ./start-notebook.sh
